language: python

python:

    - "2.7"

install:

    - pip install pytest

script:

    - python hello.py
    - pytest -v -rs hello_test.py

notifications:
    email:
      recipients:
          - pablo.pastormunoz@alum.uca.es
      on_success: never
      on_failure: always